name       : mpfr
version    : 3.1.6
release    : 5
source     :
    - https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz : 7a62ac1a04408614fccdc506e4844b10cf0ad2c2b1677097f8f35d3a1344a950
homepage   : http://www.mpfr.org/
license    :
    - GPL-3.0
summary    : The MPFR package contains functions for multiple precision math.
component  : system.base
description: |
    The MPFR package contains functions for multiple precision math.
emul32     : yes
devel      : yes
builddeps  :
    - gmp-32bit-devel
patterns   :
    - devel:
        - /usr/share/doc
        - /usr/share/info
setup      : |
    %configure --prefix=/usr \
               --enable-thread-safe \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
