name       : mpfr
version    : 3.1.5
release    : 4
source     :
    - https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.5.tar.xz : 015fde82b3979fbe5f83501986d328331ba8ddf008c1ff3da3c238f49ca062bc
homepage   : http://www.mpfr.org/
license    :
    - GPL-3.0
summary    : The MPFR package contains functions for multiple precision math.
component  : system.base
description: |
    The MPFR package contains functions for multiple precision math.
emul32     : yes
devel      : yes
builddeps  :
    - gmp-32bit-devel
patterns   :
    - devel:
        - /usr/share/doc
        - /usr/share/info
setup      : |
    %configure --prefix=/usr \
               --enable-thread-safe \
               --disable-static
build      : |
    %make
install    : |
    %make_install
