name        : mpfr
version     : 3.1.2
release     : 3
source      :
    - http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.2.tar.xz : 399d0f47ef6608cc01d29ed1b99c7faff36d9994c45f36f41ba250147100453b
homepage    : http://www.mpfr.org/
license     :
    - GPL-3.0
summary     : The MPFR package contains functions for multiple precision math.
description : |
    The MPFR package contains functions for multiple precision math.
emul32     : yes
devel      : yes
patterns   :
    - devel: [/usr/share/doc, /usr/share/info]
setup      : |
    %configure --prefix=/usr \
               --enable-thread-safe \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
