name       : mpfr
version    : 4.0.2
release    : 7
source     :
    - https://ftp.gnu.org/gnu/mpfr/mpfr-4.0.2.tar.xz : 1d3be708604eae0e42d578ba93b390c2a145f17743a744d8f3f8c2ad5855a38a
homepage   : http://www.mpfr.org/
license    : GPL-3.0-or-later
summary    : The MPFR package contains functions for multiple precision math.
component  : system.base
description: |
    The MPFR package contains functions for multiple precision math.
emul32     : yes
devel      : yes
builddeps  :
    - gmp-32bit-devel
patterns   :
    - devel :
        - /usr/share/doc
        - /usr/share/info
setup      : |
    %configure --prefix=/usr \
               --enable-thread-safe \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
