name       : mpfr
version    : 4.1.0
release    : 9
source     :
    - https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.xz : 0c98a3f1732ff6ca4ea690552079da9c597872d30e96ec28414ee23c95558a7f
homepage   : https://www.mpfr.org/
license    : GPL-3.0-or-later
summary    : The MPFR package contains functions for multiple precision math.
component  : system.base
description: |
    The MPFR package contains functions for multiple precision math.
emul32     : yes
devel      : yes
builddeps  :
    - gmp-32bit-devel
patterns   :
    - devel :
        - /usr/share/doc
        - /usr/share/info
setup      : |
    %configure --enable-thread-safe \
               --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
